/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface NewPost {
  'coverImageUrl' : string,
  'title' : string,
  'content' : string,
  'slug' : string,
  'tags' : Array<string>,
  'publishedAt' : bigint,
  'author' : string,
  'excerpt' : string,
}
export interface Post {
  'id' : bigint,
  'coverImageUrl' : string,
  'title' : string,
  'content' : string,
  'published' : boolean,
  'createdAt' : bigint,
  'slug' : string,
  'tags' : Array<string>,
  'publishedAt' : bigint,
  'author' : string,
  'updatedAt' : bigint,
  'excerpt' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPost' : ActorMethod<[NewPost], undefined>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPostById' : ActorMethod<[bigint], Post>,
  'getPostBySlug' : ActorMethod<[string], Post>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllPosts' : ActorMethod<[], Array<Post>>,
  'listPublishedPosts' : ActorMethod<[], Array<Post>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'togglePublished' : ActorMethod<[bigint], undefined>,
  'updatePost' : ActorMethod<[bigint, NewPost], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];