/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const NewPost = IDL.Record({
  'coverImageUrl' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'publishedAt' : IDL.Int,
  'author' : IDL.Text,
  'excerpt' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'coverImageUrl' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'published' : IDL.Bool,
  'createdAt' : IDL.Int,
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'publishedAt' : IDL.Int,
  'author' : IDL.Text,
  'updatedAt' : IDL.Int,
  'excerpt' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPost' : IDL.Func([NewPost], [], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPostById' : IDL.Func([IDL.Nat], [Post], ['query']),
  'getPostBySlug' : IDL.Func([IDL.Text], [Post], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'listPublishedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'togglePublished' : IDL.Func([IDL.Nat], [], []),
  'updatePost' : IDL.Func([IDL.Nat, NewPost], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const NewPost = IDL.Record({
    'coverImageUrl' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'publishedAt' : IDL.Int,
    'author' : IDL.Text,
    'excerpt' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'coverImageUrl' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'published' : IDL.Bool,
    'createdAt' : IDL.Int,
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'publishedAt' : IDL.Int,
    'author' : IDL.Text,
    'updatedAt' : IDL.Int,
    'excerpt' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPost' : IDL.Func([NewPost], [], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPostById' : IDL.Func([IDL.Nat], [Post], ['query']),
    'getPostBySlug' : IDL.Func([IDL.Text], [Post], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'listPublishedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'togglePublished' : IDL.Func([IDL.Nat], [], []),
    'updatePost' : IDL.Func([IDL.Nat, NewPost], [], []),
  });
};

export const init = ({ IDL }) => { return []; };